### ISSUE TITLE
运行run_log.py报错ModuleNotFoundError: No module named 'env.stock_raw.envs.stock_base_env_cython'

### ISSUE THREAD

**Issue by glyace** [jidiai/Competition_RL4Stock#1]
在运行run_log.py时报ModuleNotFoundError: No module named 'env.stock_raw.envs.stock_base_env_cython'，在文件夹中有stock_base_env_cython.cpython-37m-x86_64-linux-gnu.so文件，请帮忙解答谢谢

设备：M2 Mac mini，mac os 14.1.1

Traceback (most recent call last):
  File "run_log.py", line 11, in <module>
    from env.chooseenv import make
  File "/Users/zyma/learning/RL/competition/2023stock/Competition_RL4Stock/env/__init__.py", line 2, in <module>
    from .kafang_stock import *
  File "/Users/zyma/learning/RL/competition/2023stock/Competition_RL4Stock/env/kafang_stock.py", line 17, in <module>
    from .stock_raw.envs.stock_base_env_cython import StockBaseEnvCython
ModuleNotFoundError: No module named 'env.stock_raw.envs.stock_base_env_cython'

**Comment by ligvxi** [comment]
same error

**Comment by cotZhong** [comment]
same error, maybe because of env path(x

**Comment by gentle-R** [comment]
same error

**Comment by 1nnoh** [comment]
same error，
MacBook M1 Pro，mac os 14.1.1

**Comment by wangjitao1024** [comment]
"You can try replacing the .so file in the GitHub repository with the one from this archive to see if it resolves the error."
[stock_base_env_cython.cpython-37m-darwin.so.zip](https://github.com/jidiai/Competition_RL4Stock/files/13769690/stock_base_env_cython.cpython-37m-darwin.so.zip)

**Comment by glyace** [comment]
@wangjitao1024 Thx, it solves the problem. However another file-missing problem is raised...
"ModuleNotFoundError: No module named 'env.stock_raw.mock_market_common.mock_market_data_cython'"
Please help with solving it. thx a lot

**Comment by wangjitao1024** [comment]
For Mac users using the ARM chip architecture, replace the two .so files in the repository with two .so files in the .zip file.
[Downloads.zip](https://github.com/jidiai/Competition_RL4Stock/files/13772131/Downloads.zip)
